# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'import datetime import os  root = os.path.join(''..'', ''food'') for directory, subdir_list, file_list in os.walk(root):     for name in file_list:         source_name = os.path.join(directory, name)         timestamp = os.path.getmtime(source_name)         modified_date = str(datetime.datetime.fromtimestamp(timestamp)).replace('':'', ''.'')         target_name = os.path.join(directory, f''{modified_date}_{name}'')          print(f''Renaming: {source_name} to: {target_name}'')          os.rename(source_name, target_name)'